### ISSUE TITLE
Why string instead of []byte?

### ISSUE THREAD

**Issue by maxhawkins** [pions/sdp#10]
Is there any reason why the parser's Unmarshal function takes a `string` instead of a `[]byte` like other Go marshalers?

I think there might be a performance penalty with using a string.

Also, would it ever make sense for `Marshal` to return an error? I haven't read the sdp spec, but I imagine there are some length limits or something.

**Comment by trivigy** [comment]
@maxhawkins I think the reason I did it as string was because of backward compatibility with the existing code. This was done a while back.

**Comment by maxhawkins** [comment]
Makes sense. Does the new API look OK?
